---
platform: linux

inputs:
- name: concourse-tasks
- name: domaininfo

outputs:
- name: certoutput

params:
  CLOUDFLARE_INI:
  CERTBOT_EMAIL:
  STAGING:

run:
  path: concourse-tasks/tasks/certbot-getcert/task.sh
