---
platform: linux

inputs:
- name: concourse-tasks

outputs:
- name: certoutput

params:
  CLOUDFLARE_INI:
  CERT_DOMAINS:
  CERTBOT_EMAIL:
  WILDCARD_CERT:
  STAGING:

run:
  path: concourse-tasks/tasks/certbot-getcert/task.sh
